In [17]:
import pandas as pd
import numpy as np

In [18]:
df_train = pd.read_csv('../data/train.csv')

C:\Users\yizhe\AppData\Local\Temp\ipykernel_4424\788172147.py:1: DtypeWarning: Columns (41) have mixed types. Specify dtype option on import or set low_memory=False.
  df_train = pd.read_csv('../data/train.csv')

In [19]:
df_train.head()

,id,Tranc_YearMonth,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,...,vacancy,pri_sch_affiliation,pri_sch_latitude,pri_sch_longitude,sec_sch_nearest_dist,sec_sch_name,cutoff_point,affiliation,sec_sch_latitude,sec_sch_longitude
0,88471,2016-05,KALLANG/WHAMPOA,4 ROOM,3B,UPP BOON KENG RD,10 TO 12,90.0,Model A,2006,...,78,1,1.317659,103.882504,1138.633422,Geylang Methodist School,224,0,1.317659,103.882504
1,122598,2012-07,BISHAN,5 ROOM,153,BISHAN ST 13,07 TO 09,130.0,Improved,1987,...,45,1,1.349783,103.854529,447.894399,Kuo Chuan Presbyterian Secondary School,232,0,1.350110,103.854892
2,170897,2013-07,BUKIT BATOK,EXECUTIVE,289B,BT BATOK ST 25,13 TO 15,144.0,Apartment,1997,...,39,0,1.345245,103.756265,180.074558,Yusof Ishak Secondary School,188,0,1.342334,103.760013
3,86070,2012-04,BISHAN,4 ROOM,232,BISHAN ST 22,01 TO 05,103.0,Model A,1992,...,20,1,1.354789,103.844934,389.515528,Catholic High School,253,1,1.354789,103.844934
4,153632,2017-12,YISHUN,4 ROOM,876,YISHUN ST 81,01 TO 03,83.0,Simplified,1987,...,74,0,1.416280,103.838798,312.025435,Orchid Park Secondary School,208,0,1.414888,103.838335

In [20]:
df_train.dtypes.value_counts()

int64      32
float64    25
object     20
Name: count, dtype: int64

In [21]:
num_col = df_train.select_dtypes(include=['int64']).columns
float_col = df_train.select_dtypes(include=['float64']).columns
cat_col = df_train.select_dtypes(include=['object']).columns

Clean num_col first:

1. Check negative values
2. check logic violations

In [22]:
num_col_null_counts = df_train[num_col].isnull().sum()
num_col_null_counts[num_col_null_counts != 0]

Series([], dtype: int64)

In [25]:
df_train[num_col].head()

,id,lease_commence_date,Tranc_Year,Tranc_Month,mid_storey,lower,upper,mid,hdb_age,max_floor_lvl,...,3room_rental,other_room_rental,hawker_food_stalls,hawker_market_stalls,bus_interchange,mrt_interchange,vacancy,pri_sch_affiliation,cutoff_point,affiliation
0,88471,2006,2016,5,11,10,12,11,15,25,...,0,0,84,60,0,0,78,1,224,0
1,122598,1987,2012,7,8,7,9,8,34,9,...,0,0,80,77,1,1,45,1,232,0
2,170897,1997,2013,7,14,13,15,14,24,16,...,0,0,84,95,1,0,39,0,188,0
3,86070,1992,2012,4,3,1,5,3,29,11,...,0,0,32,86,1,1,20,1,253,1
4,153632,1987,2017,12,2,1,3,2,34,4,...,0,0,45,0,0,0,74,0,208,0

In [ ]:
non_negative_num_col = [col for col in num_col if any(keyword in col.lower() for keyword in ['count', 'num', 'quantity', 'amount', 'total'])]